# Generated by Django 4.2.2 on 2023-06-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_person_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_image',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='team_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.team')),
            ],
        ),
        migrations.CreateModel(
            name='person_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.person')),
            ],
        ),
    ]
