# Generated by Django 4.2.2 on 2023-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_person_user_image_team_image_alter_person_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='tiktok',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='twitter',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='youtube',
            field=models.URLField(default=''),
        ),
    ]
