# Generated by Django 4.2.2 on 2023-06-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_account_facebook_alter_account_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='tiktok',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
