# Generated by Django 4.2.2 on 2023-06-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_account_facebook_alter_account_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='youtube',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
