# Generated by Django 4.2.2 on 2023-06-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_account_facebook_alter_account_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
