# Generated by Django 4.2.2 on 2023-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_person_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='customer_name',
            field=models.CharField(max_length=30),
        ),
    ]
