# Generated by Django 4.2.2 on 2023-06-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_feedback_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_account',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='user_task',
            new_name='Tasks',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='user_team',
            new_name='Team',
        ),
    ]
