# Generated by Django 4.2.2 on 2023-06-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_person_account_alter_person_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='portfolio.task'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.team'),
        ),
    ]
