# Generated by Django 4.2.2 on 2023-07-01 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_person_account_alter_person_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
